# Generated by Django 6.0 on 2025-12-12 09:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier_csv', models.FileField(upload_to='datasets/')),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('stats_csv', models.FileField(blank=True, null=True, upload_to='stats/')),
                ('notes_numpy', models.FileField(blank=True, null=True, upload_to='notes_numpy/')),
            ],
        ),
    ]
